version: "3.8"

services:
  isopod:
    build: .
    container_name: isopod
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Updated to use relative path './servers' for cross-platform compatibility.
      # The 'servers' directory will be created next to the isopod-compose.yml file.
      - ./servers:/DATA/AppData/isopod/servers
    environment:
      - SERVERS_DIR=/DATA/AppData/isopod/servers
